"""ODE samplers for flow matching.

At inference time, samples are generated by integrating the learned ODE
backward from t=1 (noise) to t=0 (data):

    dx/dt = v_theta(x(t), t),   x(1) ~ N(0, I)

Three solvers are provided, in order of NFE efficiency:
    - EulerSampler:    1 NFE/step, O(dt) global error. Fast but needs ~50 steps.
    - RK4Sampler:      4 NFEs/step, O(dt^4) global error. Good at 10-20 steps.
    - AdaptiveSampler: Variable NFEs, automatic step sizing. Best accuracy/NFE
                       ratio for complex trajectories. Requires torchdiffeq.

All samplers accept the same interface: sampler.sample(n, device) → tensor.

See also:
    dev/flow_matching/numerical_ode_integration.md
    dev/flow_matching/numerical_runge_kutta.md
"""

from __future__ import annotations

import logging
from typing import Callable

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helper: wrap model to accept consistent (x, t_scalar) inputs
# ---------------------------------------------------------------------------

def _velocity_fn(model: nn.Module, x: torch.Tensor, t: float) -> torch.Tensor:
    """Evaluate v_theta(x, t) with t broadcast to the batch dimension."""
    t_tensor = torch.full((x.shape[0],), t, device=x.device, dtype=x.dtype)
    return model(x, t_tensor)


# ---------------------------------------------------------------------------
# Euler sampler
# ---------------------------------------------------------------------------

class EulerSampler:
    """Euler-method ODE sampler.

    Integrates backward from t=1 to t=0 with uniform step size:

        x_{t - dt} = x_t - dt * v_theta(x_t, t)

    Cost: n_steps NFEs.

    Args:
        model:   Trained velocity network.
        n_steps: Number of integration steps. 50 is a safe default;
                 well-reflowed models may work at 10-20.

    Example::

        sampler = EulerSampler(model, n_steps=50)
        images = sampler.sample(16, device="mps")  # (16, C, H, W)
    """

    def __init__(self, model: nn.Module, n_steps: int = 50):
        self.model = model
        self.n_steps = n_steps

    @torch.no_grad()
    def sample(
        self,
        n: int,
        image_shape: tuple[int, ...],
        device: str | torch.device | None = None,
    ) -> torch.Tensor:
        """Generate n samples.

        Args:
            n:           Number of samples (batch size).
            image_shape: Shape of one sample, e.g. (1, 28, 28) for MNIST.
            device:      Target device. Uses model device if None.

        Returns:
            Generated samples, shape (n, *image_shape).
        """
        device = device or next(self.model.parameters()).device
        self.model.eval()

        dt = 1.0 / self.n_steps
        x = torch.randn(n, *image_shape, device=device)

        for step in range(self.n_steps):
            t = 1.0 - step * dt          # counts down: 1.0, 1-dt, ..., dt
            x = x - dt * _velocity_fn(self.model, x, t)

        return x


# ---------------------------------------------------------------------------
# RK4 sampler
# ---------------------------------------------------------------------------

class RK4Sampler:
    """4th-order Runge-Kutta ODE sampler.

    Uses 4 velocity evaluations per step to achieve O(dt^4) global error,
    allowing accurate integration with far fewer steps than Euler.

    Update rule:
        k1 = v(x,         t        )
        k2 = v(x - dt/2*k1, t - dt/2)
        k3 = v(x - dt/2*k2, t - dt/2)
        k4 = v(x - dt*k3,   t - dt  )
        x_{t-dt} = x - (dt/6)(k1 + 2k2 + 2k3 + k4)

    Cost: 4 * n_steps NFEs. Typically needs only 10-20 steps for quality
    comparable to Euler at 50-100 steps.

    Args:
        model:   Trained velocity network.
        n_steps: Number of integration steps.
    """

    def __init__(self, model: nn.Module, n_steps: int = 20):
        self.model = model
        self.n_steps = n_steps

    @torch.no_grad()
    def sample(
        self,
        n: int,
        image_shape: tuple[int, ...],
        device: str | torch.device | None = None,
    ) -> torch.Tensor:
        """Generate n samples.

        Args:
            n:           Number of samples.
            image_shape: Shape of one sample.
            device:      Target device.

        Returns:
            Generated samples, shape (n, *image_shape).
        """
        device = device or next(self.model.parameters()).device
        self.model.eval()

        dt = 1.0 / self.n_steps
        x = torch.randn(n, *image_shape, device=device)

        for step in range(self.n_steps):
            t = 1.0 - step * dt

            k1 = _velocity_fn(self.model, x,                   t)
            k2 = _velocity_fn(self.model, x - 0.5 * dt * k1,  t - 0.5 * dt)
            k3 = _velocity_fn(self.model, x - 0.5 * dt * k2,  t - 0.5 * dt)
            k4 = _velocity_fn(self.model, x - dt * k3,         t - dt)

            x = x - (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)

        return x


# ---------------------------------------------------------------------------
# Adaptive sampler (requires torchdiffeq)
# ---------------------------------------------------------------------------

class AdaptiveSampler:
    """Adaptive-step ODE sampler using the Dormand-Prince (dopri5) method.

    Automatically adjusts step size to maintain a target error tolerance,
    providing the best accuracy-per-NFE ratio for complex trajectories.

    Requires the ``torchdiffeq`` library::

        pip install torchdiffeq

    Args:
        model:   Trained velocity network.
        rtol:    Relative error tolerance (default 1e-4).
        atol:    Absolute error tolerance (default 1e-4).
        method:  ODE solver method (default ``"dopri5"``).
    """

    def __init__(
        self,
        model: nn.Module,
        rtol: float = 1e-4,
        atol: float = 1e-4,
        method: str = "dopri5",
    ):
        self.model = model
        self.rtol = rtol
        self.atol = atol
        self.method = method

        try:
            from torchdiffeq import odeint  # noqa: F401
            self._odeint = odeint
        except ImportError as e:
            raise ImportError(
                "AdaptiveSampler requires torchdiffeq: pip install torchdiffeq"
            ) from e

    @torch.no_grad()
    def sample(
        self,
        n: int,
        image_shape: tuple[int, ...],
        device: str | torch.device | None = None,
    ) -> torch.Tensor:
        """Generate n samples.

        Args:
            n:           Number of samples.
            image_shape: Shape of one sample.
            device:      Target device.

        Returns:
            Generated samples, shape (n, *image_shape).
        """
        device = device or next(self.model.parameters()).device
        self.model.eval()

        x1 = torch.randn(n, *image_shape, device=device)

        # torchdiffeq expects the ODE in the forward direction.
        # We integrate from t=1 to t=0 by reversing the time span.
        def ode_fn(t: torch.Tensor, x: torch.Tensor) -> torch.Tensor:
            # t is a scalar tensor; velocity is in the backward direction
            return -_velocity_fn(self.model, x, t.item())

        t_span = torch.tensor([1.0, 0.0], device=device)
        trajectory = self._odeint(ode_fn, x1, t_span, rtol=self.rtol, atol=self.atol, method=self.method)
        # trajectory shape: (2, n, *image_shape); take the final time point
        return trajectory[-1]


# ---------------------------------------------------------------------------
# Convenience factory
# ---------------------------------------------------------------------------

def build_sampler(
    method: str,
    model: nn.Module,
    **kwargs,
) -> EulerSampler | RK4Sampler | AdaptiveSampler:
    """Construct a sampler by name.

    Args:
        method: ``"euler"``, ``"rk4"``, or ``"adaptive"``.
        model:  Trained velocity network.
        **kwargs: Forwarded to the sampler constructor.

    Returns:
        Sampler instance.

    Example::

        sampler = build_sampler("rk4", model, n_steps=20)
        samples = sampler.sample(16, image_shape=(1, 28, 28))
    """
    registry = {
        "euler": EulerSampler,
        "rk4": RK4Sampler,
        "adaptive": AdaptiveSampler,
    }
    if method not in registry:
        raise ValueError(f"Unknown sampler '{method}'. Choose from {list(registry.keys())}.")
    return registry[method](model, **kwargs)
